OPM_arch_Project/accounts_app/urls.py
from django.urls import path, include

from OPM_arch_Project.accounts_app.views import LoginUserView, ProfileUserView, LogOutUserView, \
    ProfileEditUserView, check_auth_user, ProfileDetailsUserView, ChangePasswordUserView, check_auth_success

urlpatterns = [
    path('auth/', include([
        path("", check_auth_user, name='auth'),
        path("success/", check_auth_success, name="auth_success"),
    ])),
    path("login/", LoginUserView.as_view(), name="login_user"),
    path("logout/", LogOutUserView.as_view(), name="logout_user"),

    path("profile/", include([
        path("", ProfileUserView.as_view(), name="profile_user"),
        path("<int:pk>/", include([
            path("details/", ProfileDetailsUserView.as_view(), name="profile_details"),
            path("edit/", ProfileEditUserView.as_view(), name="profile_edit"),
        ])),
    ]),
         ),
    path('user/', include([
        path("password/", ChangePasswordUserView.as_view(), name="user_change_password"),
    ])),
]

OPM_arch_Project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('chaining/', include('smart_selects.urls')),
    path('', include('OPM_arch_Project.web_app.urls')),
    path('accounts/', include('OPM_arch_Project.accounts_app.urls')),
    path('clients/', include('OPM_arch_Project.clients_app.urls')),
    path('projects/', include('OPM_arch_Project.projects_app.urls')),
]

OPM_arch_Project/accounts_app/models.py
from enum import Enum

from django.contrib import admin
from django.db import models
from django.contrib.auth import models as auth_models

from OPM_arch_Project.accounts_app.managers import AppUserManager
from OPM_arch_Project.clients_app.models import Client
from OPM_arch_Project.core.model_mixins import ChoicesEnumMixin


class AppUser(auth_models.AbstractBaseUser, auth_models.PermissionsMixin):

    email = models.EmailField(
        unique=True,
        blank=False,
        null=False,
    )
    is_active = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)

    client = models.ForeignKey(
        to=Client,
        on_delete=models.DO_NOTHING,
        blank=True,
        null=True,
    )

    verification_code = models.BooleanField(
        default=False,
        blank=True,
        null=True,
    )

    objects = AppUserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    def __str__(self):
        return self.email


class SpecialityChoices(ChoicesEnumMixin, Enum):
    ARCHITECT = 'Architect'
    CIVIL_ENGINEER = 'Civil Engineer'
    MEP_ENGINEER = 'MEP Engineer'
    HVAC_ENGINEER = 'HVAC Engineer'
    ROAD_ENGINEER = 'ROAD Engineer'
    VIZ_ARTIST = '3D Artist'
    OTHER = 'Other'


class RoleChoices(ChoicesEnumMixin, Enum):
    JUNIOR = 'Junior'
    INTERMEDIATE = 'Intermediate'
    SENIOR = 'Senior'
    TEAM_LEADER = 'Team Leader'
    PROJECT_MANAGER = 'Project Manager'
    OTHER = 'Other'


class Profile(models.Model):
    PHONE_NUMBER_MAX_LENGTH = 150
    FIRST_NAME_MAX_LENGTH = 30
    LAST_NAME_MAX_LENGTH = 50

    user = models.OneToOneField(
        AppUser, on_delete=models.CASCADE, primary_key=True,
    )
    first_name = models.CharField(
        max_length=FIRST_NAME_MAX_LENGTH,
        blank=True,
        null=True,
    )
    last_name = models.CharField(
        max_length=LAST_NAME_MAX_LENGTH,
        blank=True,
        null=True,
    )
    speciality = models.CharField(
        max_length=SpecialityChoices.max_name_len(),
        choices=SpecialityChoices.choices(),
        blank=True,
        null=True,
    )
    role = models.CharField(
        max_length=RoleChoices.max_name_len(),
        choices=RoleChoices.choices(),
        blank=True,
        null=True,
    )
    date_of_birth = models.DateField(
        blank=True,
        null=True,
    )
    phone_number = models.CharField(
        max_length=PHONE_NUMBER_MAX_LENGTH,
        blank=True,
        null=True,
    )
    profile_picture = models.ImageField(
        upload_to='profile_pictures/',
        blank=True,
        null=True,
    )

    def __str__(self):
        return f"{self.user.email} - {self.first_name} {self.last_name}"

    @admin.display(description="Full Name")
    def get_name(self):
        if self.first_name is not None and self.last_name is not None:
            return f"{self.first_name} {self.last_name}"
        elif self.first_name is not None:
            return f"{self.first_name}"
        elif self.last_name is not None:
            return f"{self.last_name}"

        return

OPM_arch_Project/accounts_app/forms.py
from django.contrib.auth import forms as auth_forms, get_user_model, authenticate
from django import forms
from django.core.exceptions import ValidationError

from OPM_arch_Project.accounts_app.models import Profile
from OPM_arch_Project.core.utils import generate_verification_code, send_verification_email

UserModel = get_user_model()


class LoginUserForm(auth_forms.AuthenticationForm):

    def __init__(self, request, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs.update({
                'class': 'form-control'
            })

        self.redirect_to_password = False

    def clean(self):

        email = self.cleaned_data.get("username")
        password = self.cleaned_data.get("password")

        if email is not None and password:
            user = UserModel.objects.filter(email=email).first()
            if user and user.check_password(password) and not user.is_active and user.verification_code:
                user.is_active = True
                user.verification_code = False
                user.save()
                self.redirect_to_password = True
            self.user_cache = authenticate(
                self.request, username=email, password=password
            )
            if self.user_cache is None:
                raise self.get_invalid_login_error()
            else:
                self.confirm_login_allowed(self.user_cache)

        cleaned_data = super().clean()

        return cleaned_data


class ChangePasswordUserForm(auth_forms.PasswordChangeForm):

    def __init__(self, user, *args, **kwargs):
        super().__init__(user, *args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs.update({
                'class': 'form-control',
            })


class CheckAuthForm(forms.ModelForm):

    def clean(self):
        users_emails = UserModel.objects.values_list('email')

        for mail in users_emails:
            if self.data['email'] in mail:
                user = UserModel.objects.get(email=self.data['email'])
                if not user.is_active and not user.verification_code:
                    email = self.data['email']
                    verification_code = generate_verification_code(length=10)
                    send_verification_email(email, verification_code)

                    user.verification_code = True
                    user.set_password(verification_code)
                    user.save()
                    return

                elif user.verification_code:
                    raise ValidationError('Your verification email is already sent. '
                                          'Please check your email and follow the instructions.')

        raise ValidationError('This email is not a valid email address!')

    class Meta:
        model = UserModel
        fields = ('email',)


class CreateUserForm(auth_forms.UserCreationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs.update({
                'class': 'form-control'
            })
        self.fields['password1'].required = False
        self.fields['password2'].required = False
        self.fields['password1'].widget.attrs['hidden'] = 'hidden'
        self.fields['password2'].widget.attrs['hidden'] = 'hidden'

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if email:
            # Converting email to lowercase
            email = email.lower()
            existing_users = UserModel.objects.filter(email__iexact=email)
            if existing_users.exists():
                raise forms.ValidationError("A user with that email address already exists.")
        return email

    def save(self, commit=True):
        user = super().save(commit=False)

        # Generating default password
        default_password = generate_verification_code(length=12)

        user.set_password(default_password)

        # Converting email to lowercase before saving to DB
        user.email = user.email.lower()

        if commit:
            user.save()
            if hasattr(self, "save_m2m"):
                self.save_m2m()
        return user

    class Meta(auth_forms.UserCreationForm.Meta):
        model = UserModel
        fields = ['email', 'client', ]
        field_classes = {"email": forms.EmailField}
        help_texts = {
            'email': 'Enter your email address.'
        }


class EditUserForm(auth_forms.UserChangeForm):
    class Meta(auth_forms.UserChangeForm.Meta):
        model = UserModel
        fields = "__all__"


class EditProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = '__all__'
        exclude = ('user',)

        widgets = {
            'first_name': forms.TextInput(
                attrs={'placeholder': 'First Name'},
            ),
            'last_name': forms.TextInput(
                attrs={'placeholder': 'Last Name'},
            ),
            'profile_picture': forms.ClearableFileInput(),
            'date_of_birth': forms.DateInput(
                attrs={'type': 'date'},
            ),
        }

OPM_arch_Project/accounts_app/views.py
from django.contrib.auth import mixins as auth_mixins, get_user_model
from django.urls import reverse_lazy
from django.views import generic as views
from django.contrib.auth import views as auth_views

from django.shortcuts import render, redirect

from OPM_arch_Project.accounts_app.forms import EditProfileForm, CheckAuthForm, LoginUserForm, \
    ChangePasswordUserForm
from OPM_arch_Project.accounts_app.models import Profile

UserModel = get_user_model()


class LoginUserView(auth_views.LoginView):
    template_name = 'accounts_app/login_user.html'
    redirect_authenticated_user = True
    form_class = LoginUserForm

    def form_valid(self, form):
        result = super().form_valid(form)

        if form.redirect_to_password:
            return redirect('user_change_password')

        return result


class LogOutUserView(auth_views.LogoutView):
    template_name = 'accounts_app/logout_user.html'


class ChangePasswordUserView(auth_views.PasswordChangeView):
    template_name = 'accounts_app/change_password_user.html'
    form_class = ChangePasswordUserForm
    success_url = reverse_lazy('profile_user')


def check_auth_user(request):
    form = CheckAuthForm()
    user = request.user

    if request.method == 'POST':
        form = CheckAuthForm(request.POST)

        if form.is_valid():
            return check_auth_success(request)

    context = {
        'form': form,
        'user': user,
    }
    return render(request, 'accounts_app/check_auth.html', context=context)


def check_auth_success(request):

    email = request.POST.get('email', None)
    user = UserModel.objects.filter(email=email).first()
    if user and user.verification_code:

        return render(request, 'accounts_app/check_auth_success.html')

    return render(request, template_name='404.html')


class ProfileUserView(auth_mixins.LoginRequiredMixin, views.ListView):
    model = UserModel
    template_name = 'accounts_app/profile_user.html'


class ProfileDetailsUserView(auth_mixins.LoginRequiredMixin, views.DetailView):
    model = UserModel
    template_name = 'accounts_app/profile_details.html'


class ProfileEditUserView(auth_mixins.LoginRequiredMixin, views.UpdateView):
    model = Profile
    form_class = EditProfileForm
    template_name = 'accounts_app/profile_edit.html'

    def get(self, request, *args, **kwargs):
        result = super().get(self, *args, **kwargs)

        if request.user.pk == self.object.pk or request.user.is_superuser:
            return result
        else:
            return render(request, template_name='403.html')

    def get_success_url(self, **kwargs):
        return reverse_lazy(
            'profile_user'
        )

templates/accounts_app/change_password_user.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}
{% load static %}

{% block title %}
    Edit User Page
{% endblock %}

{% block content %}
    
    <form class="post-form" method="post" action="">
    <div class="container">
            <img class="mb-4" src="{% static 'images/icons8-arch-64.png' %}" alt="logo.png" width="64" height="64">
            <h1 class="h3 mb-3 fw-normal"><strong>Change</strong> password</h1>

            <div class="row justify-content-left">
                <div class="col-lg-6">

                    {% csrf_token %}

                    {{ form|crispy }}
                    
                    
                    <button type="reset" class="btn btn-secondary" onclick="history.back()">Cancel</button>
                    
                    <button type="submit" class="btn btn-primary">Submit</button>

                </div>
            </div>
        </div>
    </form>
    
{% endblock %}

templates/accounts_app/check_auth.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_filters %}

{% block title %}

    Check Auth Page

{% endblock %}

{% block content %}

    <form class="post-form" method="post" action="">
        <div class="container py-4">
            <img class="mb-4" src="{% static 'images/icons8-arch-64.png' %}" alt="logo.png" width="64" height="64">
            <h1 class="h3 mb-3 fw-normal"><strong>Sign</strong> Up</h1>

            <div class="row justify-content-left">
                <div class="col-lg-5">

                    {% csrf_token %}

                    {{ form|crispy }}

                    <button class="btn btn-primary">Sign Up</button>
                    or <a href="{% url 'login_user' %}">Log In</a>
                </div>
            </div>
        </div>
    </form>

{% endblock %}

templates/accounts_app/check_auth_success.html
{% extends 'base.html' %}

{% block title %}

    Authentication Success

{% endblock %}

{% block content %}

    <meta http-equiv="refresh" content="10;{% url 'index' %}">
     
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12 ">
                <div class="col-lg-12 text-center">
                    <h1 class="fw-bold">Authentication is successful!</h1>


                    <h3 class="h2">
                        Please check your email for more instructions.
                    </h3>

                    <p>Shortly, you will be redirected to Log In page.</p>

                    <a href="{% url 'login_user' %}">
                        <input class="btn" type="submit" value="or click Here">
                    </a>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

templates/accounts_app/login_user.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}
{% load static %}

{% block title %}
    Login User Page
{% endblock %}

{% block content %}

    <form class="post-form" method="post" action="{% url 'login_user' %}?next={{ next }}">
        <div class="container py-4">
            <img class="mb-4" src="{% static 'images/icons8-arch-64.png' %}" alt="logo.png" width="64" height="64">
            <h1 class="h3 mb-3 fw-normal"><strong>Log</strong> In</h1>

            <div class="row justify-content-left">
                <div class="col-lg-5">

                    {% csrf_token %}

                    {{ form|crispy }}

                    <button class="btn btn-primary">Log In</button>
                    or <a href="{% url 'auth' %}">Sign Up</a>
                </div>
            </div>
        </div>
    </form>

{% endblock %}

templates/accounts_app/logout_user.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Log Out User Page</title>
</head>
<body>
    <h1>You have successfully logged out!</h1>
    
    <a href="{% url 'index' %}"><button>Return to HOME</button></a>
    
    <input type="hidden" name="next" value="{{ next }}" />

</body>
</html>

templates/accounts_app/profile_details.html
{% extends 'base.html' %}
{% load my_tags %}

{% block title %}
    Profile Details Page
{% endblock %}

{% block content %}

    <div class="container-fluid">

            <div class="container m-1 table-responsive" style="padding: 15px">
                <div class="card border-secondary mb-3">
                    <div class="card-body text-secondary">
                        <h5 class="card-title">{{ object.email }}</h5>
                    <hr>
                        {% if object.profile.get_name %}
                            <h5 class="card-title fw-bold">{{ object.profile.get_name }}</h5>
                        {% endif %}
                        <h5 class="card-title">{{ object.profile.get_speciality_display }}</h5>
                        <h5 class="card-title">{{ object.profile.get_role_display }}</h5>
                    </div>
                </div>
            </div>

        {% if object.baseproject_set.all %}
            <div class="container m-1 table-responsive" style="padding: 15px">
                <div class="card border-secondary mb-3">
                    <div class="card-body text-dark">
                        <h5 class="card-title" style="text-align: center">Projects as
                            <i><strong>Project manager</strong></i></h5>
                    </div>
                </div>
            </div>

            {% show_projects_as_manager base_projects=object.baseproject_set.all request=request %}
        {% endif %}

        {% if object.project_set.all %}
            <div class="container m-1 table-responsive" style="padding: 15px">
                <div class="card border-secondary mb-3">
                    <div class="card-body text-dark">
                        <h5 class="card-title" style="text-align: center">Projects as
                            <i><strong>Employee</strong></i></h5>
                    </div>
                </div>
            </div>

            {% show_projects_as_employee projects=object.project_set.all request=request %}
        {% endif %}


        <a href="{% url 'projects_list' %}" style="padding: 15px">
            <input class="btn btn-primary" type="button" value="All Projects"></a>
    </div>
{% endblock %}

templates/accounts_app/profile_edit.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}
    Profile Edit Page
{% endblock %}

{% block content %}

    <div class="container">
        <h2 style="font-size: x-large; border: lightslategrey; border-style: solid; border-radius: 8px"
            class="row justify-content-center col-lg-6">{{ object.user.email }}</h2>
    </div>

    {% if object.user.client %}
        <div class="container">
            <i><a style="text-decoration: none; color: black" href="{% url 'clients_details' pk=object.user.client.pk%}"
                  class="row justify-content-center col-lg-6">part of {{ object.user.client }}</a></i>
            <br>
        </div>
    {% endif %}

    <form class="post-form" method="post" action="{% url 'profile_edit' pk=object.pk %}" enctype="multipart/form-data">

        <div class="container">
            <div class="row justify-content-left">
                <div class="col-lg-6">

                    {% csrf_token %}

                    {% crispy form %}

                    <button type="submit" class="btn btn-primary">Edit Profile</button>
                    <button type="reset" class="btn btn-secondary" onclick="history.back()">Cancel</button>
                </div>
            </div>
        </div>

    </form>


{% endblock %}

templates/accounts_app/profile_user.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    OPMarch - Profile User Page
{% endblock %}

{% block content %}

    <div class="container card-group">

        <div class="card border-secondary mb-3" style="max-width: 25rem;">
            <div class="card-header">PROFILE PICTURE</div>
            <div class="card-body text-secondary">

                {% if user.profile.profile_picture %}
                    <p>
                        <img class="img-fluid img-thumbnail" style="width:100%;height:100%;max-block-size: 400px"
                             src="{{ user.profile.profile_picture.url }}"
                             alt="profile-picture">
                    </p>
                {% else %}
                    <p>
                        <img class="img-fluid img-thumbnail" style="width:100%;height:100%;"
                             src="{% static 'images/person9.svg' %}"
                             alt="profile-icon">
                    </p>

                {% endif %}
            </div>
        </div>

        <div class="card border-secondary mb-3" style="max-width: 25rem;">
            <div class="card-header">PERSONAL INFORMATION</div>
            <div class="card-body text-secondary">
                <h5 class="card-title">First Name</h5>
                <p class="card-text">{{ user.profile.first_name|default:"Unknown" }}</p>
                <h5 class="card-title">Last Name</h5>
                <p class="card-text">{{ user.profile.last_name|default:"Unknown" }}</p>
                <h5 class="card-title">Email address</h5>
                <p class="card-text">{{ user.email|default:"Unknown" }}</p>
                <h5 class="card-title">Telephone number</h5>
                <p class="card-text">{{ user.profile.phone_number|default:"Unknown" }}</p>
                <h5 class="card-title">Date of birth</h5>
                <p class="card-text">{{ user.profile.date_of_birth|default:"Unknown" }}</p>
            </div>
        </div>

        <div class="card border-secondary mb-3" style="max-width: 25rem;">
            <div class="card-header">PROFILE INFORMATION</div>
            <div class="card-body text-secondary">
                <h5 class="card-title">Speciality</h5>
                <p class="card-text">{{ user.profile.get_speciality_display|default:"Unknown" }}</p>
                <h5 class="card-title">Role</h5>
                <p class="card-text">{{ user.profile.get_role_display|default:"Unknown" }}</p>
                <h5 class="card-title">Company</h5>
                <p class="card-text">{{ user.client|default:"Unknown" }}</p>
                <h5 class="card-title">Account type</h5>
                {% if user.is_superuser %}
                    <p class="card-text">Administrator</p>
                {% elif user.groups.all %}
                    <p class="card-text">Moderator</p>
                {% else %}
                    <p class="card-text">Viewer</p>
                {% endif %}

            </div>
        </div>

    </div>

    <div class="container card-group">
        <a href="{% url 'auth' %}">
            <div class="card-header mb-3">
                <a class="btn btn-light" href="{% url 'profile_edit' pk=user.pk %}"
                   role="button" style="border-color: lightslategray">Edit Profile
                </a>
            </div>
        </a>
    </div>

{% endblock %}

templates/accounts_app/user_change_password.html
{% extends 'base.html' %}

{% block title %}
    Edit User Page
{% endblock %}

{% block content %}
    
    <form method="post" action="">
        {% csrf_token %}

        {{ form.as_p }}        
        
        <button type="submit">Change</button>
    </form>
    
{% endblock %}