OPM_arch_Project/projects_app/urls.py
from django.urls import include, path

from OPM_arch_Project.projects_app.views import ProjectsListView, ProjectsCreateView, ProjectsDetailsView, \
    ProjectsUpdateView, BaseProjectsUpdateView, ProjectsFilesDetailView, ProjectsFilesCreateView, \
    ProjectsFilesUpdateView, ProjectsFilesDeleteView

urlpatterns = [
    path('', include([
        path('list/', ProjectsListView.as_view(), name='projects_list'),
        path('create/', ProjectsCreateView.as_view(), name='projects_create'),
        path('<int:pk>/', include([
            path('details/', ProjectsDetailsView.as_view(), name='projects_details'),
            path('update/', ProjectsUpdateView.as_view(), name='projects_update'),
            path('update/base/', BaseProjectsUpdateView.as_view(), name='projects_base_update'),
            path('files/', include([
                path('', ProjectsFilesDetailView.as_view(), name='projects_files'),
                path('create/', ProjectsFilesCreateView.as_view(), name='projects_files_create'),
                path('<int:pk_file>/update/', ProjectsFilesUpdateView.as_view(), name='projects_files_update'),
                path('<int:pk_file>/delete/', ProjectsFilesDeleteView.as_view(), name='projects_files_delete'),
            ])),
        ])),
    ]))
]

OPM_arch_Project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('chaining/', include('smart_selects.urls')),
    path('', include('OPM_arch_Project.web_app.urls')),
    path('accounts/', include('OPM_arch_Project.accounts_app.urls')),
    path('clients/', include('OPM_arch_Project.clients_app.urls')),
    path('projects/', include('OPM_arch_Project.projects_app.urls')),
]

OPM_arch_Project/projects_app/models.py
from datetime import datetime
from enum import Enum

from django.contrib import admin
from django.contrib.auth import get_user_model
from django.db import models

from smart_selects import db_fields as smart_fields

from OPM_arch_Project.accounts_app.models import AppUser
from OPM_arch_Project.clients_app.models import Municipality, City, Client
from OPM_arch_Project.core.model_mixins import ChoicesEnumMixin, Timestamp
from OPM_arch_Project.core.validators import validate_file_size

UserModel = get_user_model()


class ProjectTypeChoices(ChoicesEnumMixin, Enum):
    SINGLE_HOUSE = 'Single House'
    ROW_HOUSES = 'Row Houses'
    MULTI_FAMILY_SMALL = 'Small Multi-Family building'
    MULTI_FAMILY_MEDIUM = 'Medium Multi-Family building'
    MULTI_FAMILY_BIG = 'Big Multi-Family building'
    OFFICE_BUILDING = 'Office building'
    PUBLIC_BUILDING = 'Public building'
    RENOVATION = 'Renovation'
    OTHER = 'Other'


class ProjectPhaseChoices(ChoicesEnumMixin, Enum):
    PRE_DESIGN = 'Pre-design'
    DESIGN = 'Design'
    PERMISSION = 'Permission'
    EXECUTIVE = 'Executive'
    OTHER = 'Other'


class ProjectStatusChoices(ChoicesEnumMixin, Enum):
    PENDING = 'Pending'
    APPROVED = 'Approved'
    REJECTED = 'Rejected'
    CANCELLED = 'Cancelled'
    COMPLETED = 'Completed'


class ProjectProgressChoices(ChoicesEnumMixin, Enum):
    PENDING = 'Pending'
    IN_PROGRESS = 'In Progress'
    COMPLETED = 'Completed'


class BaseProject(Timestamp, models.Model):
    NAME_MAX_LENGTH = 150

    client = models.ForeignKey(
        Client,
        on_delete=models.DO_NOTHING,
        blank=False,
        null=False,
    )
    name = models.CharField(
        max_length=NAME_MAX_LENGTH,
        blank=False,
        null=False,
    )
    municipality = models.ForeignKey(
        Municipality,
        on_delete=models.DO_NOTHING,
        blank=False,
        null=False,
    )
    city = smart_fields.ChainedForeignKey(
        City,
        chained_field='municipality',
        chained_model_field='municipality',
        show_all=False,
        auto_choose=True,
        sort=True,
        on_delete=models.DO_NOTHING,
        blank=False,
        null=False,
    )
    project_type = models.CharField(
        max_length=ProjectTypeChoices.max_name_len(),
        choices=ProjectTypeChoices.choices(),
        blank=False,
        null=False,
    )
    project_phase = models.CharField(
        max_length=ProjectPhaseChoices.max_name_len(),
        choices=ProjectPhaseChoices.choices(),
        blank=False,
        null=False,
    )
    project_manager = models.ForeignKey(
        UserModel,
        on_delete=models.DO_NOTHING,
        limit_choices_to={"is_staff": True},
        blank=False,
        null=False,
    )

    def __str__(self):
        return f"{self.client} - {self.name}"


class Project(Timestamp, models.Model):

    base_project = models.OneToOneField(
        BaseProject,
        on_delete=models.CASCADE,
        primary_key=True,
    )
    employees = models.ManyToManyField(
        UserModel,
        limit_choices_to={"client__is_main": True},
        default=None,
        blank=True,
    )
    start_date = models.DateField(
        blank=True,
        null=True,
    )
    end_date = models.DateField(
        blank=True,
        null=True,
    )
    status = models.CharField(
        max_length=ProjectStatusChoices.max_name_len(),
        choices=ProjectStatusChoices.choices(),
        blank=True,
        null=True,
    )
    progress = models.CharField(
        max_length=ProjectProgressChoices.max_name_len(),
        choices=ProjectProgressChoices.choices(),
        blank=True,
        null=True,
    )

    def __str__(self):
        return f"{self.base_project}"

    def get_project_timeframe(self):
        if self.start_date and self.end_date:
            start_date = str(self.start_date)
            end_date = str(self.end_date)
            timeframe = datetime.strptime(end_date, "%Y-%m-%d") - datetime.strptime(start_date, "%Y-%m-%d")

            return timeframe.days

    @admin.display(description="Client")
    def get_client_name(self):
        return self.base_project.client


class ProjectFile(Timestamp, models.Model):
    TITLE_MAX_LENGTH = 25

    title = models.CharField(
        max_length=TITLE_MAX_LENGTH,
    )
    file = models.FileField(
        upload_to="media/projects_files",
        validators=(
            validate_file_size,
        )
    )
    project = models.ForeignKey(
        to=Project,
        on_delete=models.RESTRICT,
    )
    uploaded_by = models.ForeignKey(
        to=UserModel,
        on_delete=models.RESTRICT,
    )

    def __str__(self):
        return f"{self.project.base_project.name} - {self.title}"


class ProjectComment(Timestamp, models.Model):
    TEXT_MAX_LENGTH = 300

    text = models.TextField(
        max_length=TEXT_MAX_LENGTH,
        blank=False,
        null=False,
    )
    project = models.ForeignKey(
        to=BaseProject,
        on_delete=models.RESTRICT,
    )
    user = models.ForeignKey(
        to=UserModel,
        on_delete=models.RESTRICT,
    )

    def __str__(self):
        return f"{self.user} - {self.project}"

    class Meta:
        ordering = ["created_at"]

OPM_arch_Project/projects_app/forms.py
from django import forms

from OPM_arch_Project.projects_app.models import BaseProject, Project, ProjectComment, ProjectFile


class ProjectsCreateForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs.update({
                'class': 'form-control'
            })

    class Meta:
        model = BaseProject
        fields = '__all__'


class BaseProjectUpdateForm(forms.ModelForm):

    class Meta:
        model = BaseProject
        fields = '__all__'
        exclude = ['client']


class ProjectsUpdateForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs.update({
                'class': 'form-control'
            })

    class Meta:
        model = Project
        fields = '__all__'
        exclude = ['base_project']
        widgets = {
            'employees': forms.CheckboxSelectMultiple(),
            'start_date': forms.DateInput(attrs={'type': 'date'}),
            'end_date': forms.DateInput(attrs={'type': 'date'}),
        }
        labels = {
            'employees': ''
        }


class ProjectsCommentForm(forms.ModelForm):

    class Meta:
        model = ProjectComment
        fields = ['text']
        labels = {
            'text': 'Message'
        }
        widgets = {
            'text': forms.Textarea(attrs={'rows': 3, 'cols': 12})
        }


class ProjectsFilesCreateForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):

        self.request = kwargs.pop('request', None)
        super().__init__(*args, **kwargs)

    class Meta:
        model = ProjectFile
        fields = '__all__'


class ProjectsFilesUpdateForm(forms.ModelForm):

    class Meta:
        model = ProjectFile
        exclude = ['project', 'uploaded_by']


class ProjectsFilesDeleteForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs.update({
                'disabled': 'disabled'
            })

    class Meta:
        model = ProjectFile
        fields = '__all__'


class SearchForm(forms.Form):

    project_name = forms.CharField(
        required=False,
        widget=forms.TextInput(
            attrs={
                'placeholder': 'Search by project name...'
            }
        ),
        label=''
    )

OPM_arch_Project/projects_app/views.py
from django.core.exceptions import PermissionDenied
from django.db.models import Q
from django.http import request
from django.shortcuts import redirect, get_object_or_404
from django.urls import reverse_lazy, reverse
from django.views import generic as views
from django.contrib.auth import mixins as auth_mixins

from OPM_arch_Project.projects_app.forms import ProjectsCreateForm, ProjectsUpdateForm, ProjectsCommentForm, \
    BaseProjectUpdateForm, ProjectsFilesCreateForm, ProjectsFilesUpdateForm, ProjectsFilesDeleteForm, SearchForm
from OPM_arch_Project.projects_app.models import Project, BaseProject, ProjectComment, ProjectFile


class ProjectsListView(auth_mixins.LoginRequiredMixin, views.ListView):
    model = Project
    template_name = 'projects_app/projects_list.html'
    ordering = ['-pk']

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['search_form'] = SearchForm(self.request.GET or None)

        return context

    def get_queryset(self):
        result = super().get_queryset()
        project_name_pattern = self.request.GET.get('project_name', None)

        if self.request.user.client is None or not self.request.user.client.is_main:
            result = Project.objects.filter(base_project__client=self.request.user.client)

        if project_name_pattern:
            filter_query = Q(base_project__name__icontains=project_name_pattern)
            return result.filter(filter_query)

        return result


class ProjectsCreateView(auth_mixins.LoginRequiredMixin, auth_mixins.PermissionRequiredMixin, views.CreateView):
    model = BaseProject
    template_name = 'projects_app/projects_create.html'
    form_class = ProjectsCreateForm
    permission_required = 'projects_app.add_baseproject'

    def get_success_url(self):
        return reverse_lazy('projects_list')


class ProjectsDetailsView(auth_mixins.LoginRequiredMixin, views.DetailView):
    model = BaseProject
    template_name = 'projects_app/projects_details.html'

    def get_context_data(self, **kwargs):
        result = super().get_context_data(**kwargs)
        comments = ProjectComment.objects.filter(project=self.object.project.pk)
        first_files = ProjectFile.objects.filter(project_id=self.object.project.pk).order_by('-modified_at')[:6]
        all_files = ProjectFile.objects.filter(project_id=self.object.project.pk)
        result['all_files'] = all_files
        result['first_files'] = first_files
        result['comments'] = comments
        result['comment_form'] = ProjectsCommentForm(instance=self.request.user)
        return result

    def get(self, *args, **kwargs):
        result = super().get(*args, **kwargs)

        if not self.request.user.client.is_main and self.object.client != self.request.user.client:
            raise PermissionDenied

        return result

    def post(self, request, *args, **kwargs):
        new_comment = ProjectComment(text=request.POST.get('text'),
                                     project=self.get_object(),
                                     user=self.request.user)
        new_comment.save()
        return self.get(self, request, *args, **kwargs)


class BaseProjectsUpdateView(auth_mixins.LoginRequiredMixin, auth_mixins.PermissionRequiredMixin, views.UpdateView):
    model = BaseProject
    template_name = 'projects_app/projects_base_update.html'
    form_class = BaseProjectUpdateForm
    permission_required = 'projects_app.change_baseproject'

    def get_success_url(self):
        return reverse_lazy('projects_details', kwargs={'pk': self.object.project.pk})


class ProjectsUpdateView(auth_mixins.LoginRequiredMixin, auth_mixins.PermissionRequiredMixin, views.UpdateView):
    model = Project
    template_name = 'projects_app/projects_update.html'
    form_class = ProjectsUpdateForm
    permission_required = 'projects_app.change_project'

    def get_success_url(self):
        return reverse_lazy('projects_details', kwargs={'pk': self.object.pk})


class ProjectsFilesDetailView(auth_mixins.LoginRequiredMixin,views.DetailView):
    model = BaseProject
    template_name = 'projects_app/projects_files.html'

    def get_context_data(self, **kwargs):
        result = super().get_context_data(**kwargs)

        all_files = ProjectFile.objects.filter(project_id=self.object.project.pk).order_by('-modified_at')
        result['all_files'] = all_files
        return result

    def get(self, *args, **kwargs):
        result = super().get(*args, **kwargs)

        if not self.request.user.client.is_main and self.object.client != self.request.user.client:
            raise PermissionDenied

        return result


class ProjectsFilesCreateView(auth_mixins.LoginRequiredMixin, views.CreateView):
    model = ProjectFile
    template_name = 'projects_app/projects_files_create.html'
    form_class = ProjectsFilesCreateForm

    def get_initial(self):
        initial = super().get_initial()
        initial['project'] = self.get_project()
        initial['uploaded_by'] = self.request.user
        return initial

    def get_form(self, form_class=None):
        form = super().get_form(form_class)
        form.fields['project'].disabled = True
        form.fields['uploaded_by'].disabled = True

        return form

    def get_project(self):
        project_id = self.kwargs['pk']
        result = Project.objects.get(pk=project_id)
        return result

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['project'] = self.get_project()
        return context

    def get_success_url(self):
        return reverse_lazy('projects_details', kwargs={'pk': self.object.project.pk})

    def get(self, *args, **kwargs):
        result = super().get(*args, **kwargs)

        if (not self.request.user.is_superuser
                and self.get_project().base_project.client != self.request.user.client
                and self.request.user not in self.get_project().employees.all()):
            raise PermissionDenied

        return result


class ProjectsFilesUpdateView(auth_mixins.LoginRequiredMixin, views.UpdateView):
    model = ProjectFile
    template_name = 'projects_app/projects_files_update.html'
    form_class = ProjectsFilesUpdateForm
    context_object_name = 'file'

    def get_object(self, queryset=None):
        pk_project = self.kwargs.get('pk')
        pk_file = self.kwargs.get('pk_file')
        return get_object_or_404(ProjectFile, project__pk=pk_project, pk=pk_file)

    def get_success_url(self):
        pk_project = self.kwargs.get('pk')
        return reverse('projects_details', kwargs={'pk': pk_project})

    def get(self, *args, **kwargs):
        result = super().get(*args, **kwargs)

        if not self.request.user.is_superuser and self.object.uploaded_by != self.request.user:
            raise PermissionDenied

        return result


class ProjectsFilesDeleteView(auth_mixins.LoginRequiredMixin, views.DeleteView):
    model = ProjectFile
    template_name = 'projects_app/projects_files_delete.html'
    # form_class = ProjectsFilesDeleteForm
    context_object_name = 'file'

    def get_object(self, queryset=None):
        pk_project = self.kwargs.get('pk')
        pk_file = self.kwargs.get('pk_file')
        return get_object_or_404(ProjectFile, project__pk=pk_project, pk=pk_file)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = ProjectsFilesDeleteForm(initial={
            'title': self.object.title,
            'file': self.object.file,
            'project': self.object.project,
            'uploaded_by': self.object.uploaded_by,
        })

        return context

    def delete(self, request, *args, **kwargs):
        file = self.get_object()
        file.delete()

        return redirect(self.get_success_url)

    def get_success_url(self):
        return reverse_lazy(
            'projects_details', kwargs={'pk': self.object.project.pk}
        )

    def get(self, *args, **kwargs):
        result = super().get(*args, **kwargs)

        if not self.request.user.is_superuser and self.object.uploaded_by != self.request.user:
            raise PermissionDenied

        return result

templates/projects_app/projects.html
<style>
    .profile {
        display: inline-block;
        border: 2px solid black;
        border-radius: 100%;
        width: 30px;
        height: 30px;
        background-position: center;
        background-size: cover;
    }
</style>

<div class="container m-1 table-responsive" style="margin-top: 25px;text-align: center;horiz-align: left">
    <table class="table table-striped table-fit table-bordered table-hover">
        <thead>
        <tr>
            <th scope="col"></th>
            <th scope="col">Client</th>
            <th scope="col">Name</th>
            <th scope="col">Municipality</th>
            <th scope="col">City</th>
            <th scope="col">Type</th>
            <th scope="col">Phase</th>
            <th scope="col">Project Manager</th>
            <th scope="col">Employees</th>
        </tr>

        </thead>
        <tbody>

        {% for project in projects %}

            <tr>
                <th scope="row"><a href="{% url 'projects_details' pk=project.pk %}">
                    <button class="btn btn-dark">Details</button>
                </a></th>
                <th scope="row">{{ project.base_project.client }}</th>
                <th scope="row">{{ project.base_project.name }}</th>
                <th scope="row">{{ project.base_project.municipality }}</th>
                <th scope="row">{{ project.base_project.city }}</th>
                <th scope="row">{{ project.base_project.get_project_type_display }}</th>
                <th scope="row"
                    class="{% if project.base_project.get_project_phase_display == 'Design' %}text-danger
                                {% elif project.base_project.get_project_phase_display == 'Permission' %}text-success                        
                                {% endif %}">
                    {{ project.base_project.get_project_phase_display }}</th>
                <th scope="row">{{ project.base_project.project_manager }}</th>
                <th scope="colgroup">
                    {% for employee in project.employees.all %}

                        {% if employee.profile.profile_picture %}
                            <a href="{% url 'profile_details' pk=employee.profile.pk %}">
                                <img class="profile" src="{{ employee.profile.profile_picture.url }}"
                                     alt="profile_picture"></a>
                        {% else %}
                            <span class="profile rounded-pill" style="font-size: 15px;">
                            <a style="color: inherit;text-decoration: none"
                               href="{% url 'profile_details' pk=employee.profile.pk %}">
                            {{ employee.profile.first_name|slice:1 }}{{ employee.profile.last_name|slice:1 }}
                            </a>
                            </span>
                        {% endif %}

                    {% endfor %}
                </th>
            </tr>

        {% endfor %}

        </tbody>
    </table>
</div>

templates/projects_app/projects_base_update.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block title %}
    Project Update Page
{% endblock %}

{% block content %}

    <div class="container">
        <h2 style="font-size: x-large; border: lightslategrey; border-style: solid; border-radius: 8px"
            class="row justify-content-center col-sm-4">{{ object.name }}</h2>
    </div>

    <div class="container">
        <i><a style="text-decoration: none; color: black" href="{% url 'clients_details' pk=object.client.pk %}" 
              class="row justify-content-center col-sm-4">by {{ object.client }}</a></i>
        <br>
    </div>

    <form class="post-form" method="post" action="">
    
        <div class="container">
            <div class="row justify-content-left">
                <div class="col-sm-4">
 
                    {% csrf_token %}

                    {% crispy form %}

                    <button class="btn btn-secondary">Update</button>
                </div>
            </div>
        </div>

    </form>

{% endblock %}

templates/projects_app/projects_details.html
{% extends 'base.html' %}
{% load my_tags %}
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}
{% load static %}

{% block title %}
    Project Details Page
{% endblock %}

{% block content %}

    <div class="container m-1 table-responsive" style="padding: 15px">
        <div class="card border-secondary mb-3">
            <div class="card-body text-dark">
                <h5 class="card-title" style="text-align: center">{{ object.name }}</h5>
            </div>
        </div>
    </div>

    <div class="container m-1 table-responsive">
        <div class="row row-cols-1 row-cols-md-3 g-4">

            <div class="col">
                <div class="card shadow-sm">
                    <div class="card-header">GENERAL INFORMATION</div>
                    <div class="card-body">

                        <h5 class="card-title">Client</h5>
                        <p class="card-text">
                            <a href="{% url 'clients_details' pk=object.client.pk %}"
                               style="text-decoration: none;color: black;">
                                {{ object.client }}
                            </a>
                        </p>

                        <h5 class="card-title">Municipality</h5>
                        <p class="card-text text-secondary">{{ object.municipality }}</p>

                        <h5 class="card-title">City</h5>
                        <p class="card-text text-secondary">{{ object.city }}</p>

                        <h5 class="card-title">Project type</h5>
                        <p class="card-text text-secondary">{{ object.get_project_type_display }}</p>

                        <h5 class="card-title">Project phase</h5>
                        <p class="card-text text-secondary">{{ object.get_project_phase_display }}</p>

                        <h5 class="card-title">Project manager</h5>
                        <p class="card-text text-secondary">
                            <a href="{% url 'profile_details' pk=object.project_manager.pk %}"
                               style="text-decoration: none;color: black;">
                                {{ object.project_manager }}
                            </a>
                        </p>


                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                <a href="{% url 'projects_base_update' pk=object.pk %}">
                                    <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
                                </a>
                            </div>
                            <small class="text-body-secondary">{{ object.modified_at|timesince }} ago</small>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col">
                <div class="card shadow-sm">
                    <div class="card-header">PROJECT INFORMATION</div>
                    <div class="card-body">

                        <h5 class="card-title">Start - End date</h5>
                        <p class="card-text text-secondary">{{ object.project.start_date|default:"Unknown" }}
                            - {{ object.project.end_date|default:"Unknown" }}</p>
                        <p class="card-text text-secondary">{{ object.project.get_project_timeframe|default:"0" }}
                            days</p>

                        <h5 class="card-title">Status</h5>
                        <p class="card-text text-secondary">{{ object.project.get_status_display }}</p>

                        <h5 class="card-title">Progress</h5>
                        <p class="card-text text-secondary">{{ object.project.get_progress_display }}</p>

                        <h5 class="card-title">Employees</h5>
                        <p class="card-text text-secondary">
                            {% if object.project.employees.all %}
                                {% for employee in object.project.employees.all %}
                                    <li class="list-group-item text-secondary">
                                        <a href="{% url 'profile_details' pk=employee.pk %}"
                                           style="text-decoration: none;color: black;">
                                            {% if employee.profile.get_name %}
                                                {{ employee.profile.get_name }}
                                            {% else %}
                                                {{ employee.email }}
                                            {% endif %}
                                        </a>
                                    </li>
                                {% endfor %}
                            {% else %}
                                None
                            {% endif %}
                        </p>

                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                <a href="{% url 'projects_update' pk=object.project.pk %}">
                                    <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
                                </a>
                            </div>
                            <small class="text-body-secondary">{{ object.project.modified_at|timesince }} ago</small>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col">
                <div class="card shadow-sm">
                    <div class="card-header">
                        PROJECT RESOURCES
                        <a href="{% url 'projects_files' pk=object.pk %}">
                            <i class="bi bi-pencil-square" style="color: lightslategray"></i>
                        </a>
                    </div>
                    <div class="card-body">
                        

                            {% for file in first_files %}
                                <div class="row">
                                    <div class="col">
                                        <h5 class="card-title">{{ file.title }}</h5>
                                    </div>
                                    <div class="col" style="text-align: right">
                                        <small>{{ file.modified_at|date }}</small>
                                    </div>
                                </div>
                                <p class="card-text">
                                    <a style="text-decoration: none" href="{{ file.file.url }}" target="_blank" rel="noopener">
                                        <i class="bi bi-box-arrow-down"></i>
                                    </a>
                                    <a class="link-secondary" style="text-decoration: none">
                                    {{ file|filename|truncatechars:30 }} - {{ file.file.size|filesizeformat }}
                                    </a>

                                </p>
    
                            {% endfor %}


                        
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                            {% if all_files|length > first_files|length %}
                                <a class="btn btn-sm btn-outline-secondary" 
                                    href="{% url 'projects_files' pk=object.pk %}" role="button">View All
                                </a>
                            {% endif %}
                                <a class="btn btn-sm btn-outline-secondary" 
                                    href="{% url 'projects_files_create' pk=object.pk %}" role="button">Upload
                                </a>
                            </div>
                            <small class="text-body-secondary">{{ all_files|length }} files</small>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>

    <div class="container m-1 table-responsive">
        <div class="list-group">

            {% for comment in comments %}

                <a href="#" class="list-group-item list-group-item-action
                    {% if comment.user.client.is_main %} bg-light border-primary-subtle {% endif %}">
                    <div class="d-flex w-100 justify-content-between">
                        <h5 class="mb-1 {% if comment.user.client.is_main %} text-primary {% endif %}">{{ comment.text }}</h5>
                        <small class="text-body-secondary">{{ comment.created_at }}</small>
                    </div>
                    <br>
                    <p class="mb-1">{{ comment.user }}</p>
                    <small class="text-body-secondary">{{ comment.user.client }}</small>
                </a>

            {% endfor %}

        </div>
    </div>

    {% if request.user in object.project.employees.all or request.user.is_staff or request.user.client == object.client %}
            
        {% if request.user.client == object.client and request.user.client.is_main and not request.user.is_staff %}
        {% else %}
            {% include 'projects_app/partials/comment_form.html' %}
        {% endif %}
    {% endif %}

{% endblock %}