OPM_arch_Project/clients_app/urls.py
from django.urls import path, include

from OPM_arch_Project.clients_app.views import ClientsDetailView, ClientsCreateView, ClientsUpdateView, ClientsListView

urlpatterns = [
    path('', include([
        path('list/', ClientsListView.as_view(), name='clients_list'),
        path('create/', ClientsCreateView.as_view(), name='clients_create'),
        path('<int:pk>/', include([
            path('details/', ClientsDetailView.as_view(), name='clients_details'),
            path('update/', ClientsUpdateView.as_view(), name='clients_update'),
        ])),
    ])),
    # path('municipality/', include([
    #     path('create/', name='municipality_create'),
    #     path('<int:pk>/update/', name='municipality_update')
    # ])),
    # path('city/', include([
    #     path('create/', name='city_create'),
    #     path('<int:pk>/update/', name='city_update')
    # ]))
]

OPM_arch_Project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('chaining/', include('smart_selects.urls')),
    path('', include('OPM_arch_Project.web_app.urls')),
    path('accounts/', include('OPM_arch_Project.accounts_app.urls')),
    path('clients/', include('OPM_arch_Project.clients_app.urls')),
    path('projects/', include('OPM_arch_Project.projects_app.urls')),
]

OPM_arch_Project/clients_app/models.py
from django.core import validators
from django.db import models

from OPM_arch_Project.core.validators import check_only_digits


class Municipality(models.Model):
    MUNICIPALITY_NAME_MAX_LENGTH = 50
    PROVINCE_NAME_MAX_LENGTH = 50
    REGION_NAME_MAX_LENGTH = 50
    TEL_NUMBER_MAX_LENGTH = 30
    TEL_NUMBER_MIN_LENGTH = 5

    name = models.CharField(
        max_length=MUNICIPALITY_NAME_MAX_LENGTH,
        blank=False,
        null=False,
    )
    province = models.CharField(
        max_length=PROVINCE_NAME_MAX_LENGTH,
        blank=False,
        null=False,
    )
    region = models.CharField(
        max_length=REGION_NAME_MAX_LENGTH,
        blank=False,
        null=False,
    )
    postal_code = models.PositiveIntegerField()
    telephone_number = models.CharField(
        max_length=TEL_NUMBER_MAX_LENGTH,
        validators=(
            validators.MinLengthValidator(TEL_NUMBER_MIN_LENGTH),
            check_only_digits,
        ),
        blank=False,
        null=False,
    )
    website = models.URLField(
        blank=False,
        null=False,
    )

    class Meta:
        verbose_name_plural = 'Municipalities'

    def __str__(self):
        return self.name


class City(models.Model):
    CITY_NAME_MAX_LENGTH = 50
    TEL_CODE_MAX_LENGTH = 10
    TEL_CODE_MIN_LENGTH = 2

    name = models.CharField(
        max_length=CITY_NAME_MAX_LENGTH,
        blank=False,
        null=False,
    )
    telephone_code = models.CharField(
        max_length=TEL_CODE_MAX_LENGTH,
        validators=(
            validators.MinLengthValidator(TEL_CODE_MIN_LENGTH),
            check_only_digits,
        ),
        blank=False,
        null=False,
    )
    municipality = models.ForeignKey(
        to=Municipality,
        on_delete=models.CASCADE,
        blank=False,
        null=False,
    )

    class Meta:
        verbose_name_plural = 'Cities'

    def __str__(self):
        return self.name


class Client(models.Model):
    NAME_MAX_LENGTH = 100
    COUNTRY_MAX_LENGTH = 50
    CITY_MAX_LENGTH = 50
    STREET_NAME_MAX_LENGTH = 100
    TEL_NUMBER_MAX_LENGTH = 100
    TEL_NUMBER_MIN_LENGTH = 5

    name = models.CharField(
        max_length=NAME_MAX_LENGTH,
        unique=True,
        blank=False,
        null=False,
    )
    country = models.CharField(
        max_length=COUNTRY_MAX_LENGTH,
        blank=False,
        null=False,
    )
    city = models.CharField(
        max_length=CITY_MAX_LENGTH,
        blank=False,
        null=False,
    )
    street_name = models.CharField(
        max_length=STREET_NAME_MAX_LENGTH
    )
    street_number = models.PositiveIntegerField(
        blank=False,
        null=False,
    )
    telephone_number = models.CharField(
        max_length=TEL_NUMBER_MAX_LENGTH,
        validators=(
            validators.MinLengthValidator(TEL_NUMBER_MIN_LENGTH),
            check_only_digits,
        ),
        blank=False,
        null=False,
    )
    website = models.URLField(
        blank=True,
        null=True,
    )
    is_active = models.BooleanField(
        default=True,
    )
    is_main = models.BooleanField(
        default=False,
    )

    class Meta:
        verbose_name_plural = 'Clients'

    def __str__(self):
        return self.name

OPM_arch_Project/projects_app/models.py
from datetime import datetime
from enum import Enum

from django.contrib import admin
from django.contrib.auth import get_user_model
from django.db import models

from smart_selects import db_fields as smart_fields

from OPM_arch_Project.accounts_app.models import AppUser
from OPM_arch_Project.clients_app.models import Municipality, City, Client
from OPM_arch_Project.core.model_mixins import ChoicesEnumMixin, Timestamp
from OPM_arch_Project.core.validators import validate_file_size

UserModel = get_user_model()


class ProjectTypeChoices(ChoicesEnumMixin, Enum):
    SINGLE_HOUSE = 'Single House'
    ROW_HOUSES = 'Row Houses'
    MULTI_FAMILY_SMALL = 'Small Multi-Family building'
    MULTI_FAMILY_MEDIUM = 'Medium Multi-Family building'
    MULTI_FAMILY_BIG = 'Big Multi-Family building'
    OFFICE_BUILDING = 'Office building'
    PUBLIC_BUILDING = 'Public building'
    RENOVATION = 'Renovation'
    OTHER = 'Other'


class ProjectPhaseChoices(ChoicesEnumMixin, Enum):
    PRE_DESIGN = 'Pre-design'
    DESIGN = 'Design'
    PERMISSION = 'Permission'
    EXECUTIVE = 'Executive'
    OTHER = 'Other'


class ProjectStatusChoices(ChoicesEnumMixin, Enum):
    PENDING = 'Pending'
    APPROVED = 'Approved'
    REJECTED = 'Rejected'
    CANCELLED = 'Cancelled'
    COMPLETED = 'Completed'


class ProjectProgressChoices(ChoicesEnumMixin, Enum):
    PENDING = 'Pending'
    IN_PROGRESS = 'In Progress'
    COMPLETED = 'Completed'


class BaseProject(Timestamp, models.Model):
    NAME_MAX_LENGTH = 150

    client = models.ForeignKey(
        Client,
        on_delete=models.DO_NOTHING,
        blank=False,
        null=False,
    )
    name = models.CharField(
        max_length=NAME_MAX_LENGTH,
        blank=False,
        null=False,
    )
    municipality = models.ForeignKey(
        Municipality,
        on_delete=models.DO_NOTHING,
        blank=False,
        null=False,
    )
    city = smart_fields.ChainedForeignKey(
        City,
        chained_field='municipality',
        chained_model_field='municipality',
        show_all=False,
        auto_choose=True,
        sort=True,
        on_delete=models.DO_NOTHING,
        blank=False,
        null=False,
    )
    project_type = models.CharField(
        max_length=ProjectTypeChoices.max_name_len(),
        choices=ProjectTypeChoices.choices(),
        blank=False,
        null=False,
    )
    project_phase = models.CharField(
        max_length=ProjectPhaseChoices.max_name_len(),
        choices=ProjectPhaseChoices.choices(),
        blank=False,
        null=False,
    )
    project_manager = models.ForeignKey(
        UserModel,
        on_delete=models.DO_NOTHING,
        limit_choices_to={"is_staff": True},
        blank=False,
        null=False,
    )

    def __str__(self):
        return f"{self.client} - {self.name}"


class Project(Timestamp, models.Model):

    base_project = models.OneToOneField(
        BaseProject,
        on_delete=models.CASCADE,
        primary_key=True,
    )
    employees = models.ManyToManyField(
        UserModel,
        limit_choices_to={"client__is_main": True},
        default=None,
        blank=True,
    )
    start_date = models.DateField(
        blank=True,
        null=True,
    )
    end_date = models.DateField(
        blank=True,
        null=True,
    )
    status = models.CharField(
        max_length=ProjectStatusChoices.max_name_len(),
        choices=ProjectStatusChoices.choices(),
        blank=True,
        null=True,
    )
    progress = models.CharField(
        max_length=ProjectProgressChoices.max_name_len(),
        choices=ProjectProgressChoices.choices(),
        blank=True,
        null=True,
    )

    def __str__(self):
        return f"{self.base_project}"

    def get_project_timeframe(self):
        if self.start_date and self.end_date:
            start_date = str(self.start_date)
            end_date = str(self.end_date)
            timeframe = datetime.strptime(end_date, "%Y-%m-%d") - datetime.strptime(start_date, "%Y-%m-%d")

            return timeframe.days

    @admin.display(description="Client")
    def get_client_name(self):
        return self.base_project.client


class ProjectFile(Timestamp, models.Model):
    TITLE_MAX_LENGTH = 25

    title = models.CharField(
        max_length=TITLE_MAX_LENGTH,
    )
    file = models.FileField(
        upload_to="media/projects_files",
        validators=(
            validate_file_size,
        )
    )
    project = models.ForeignKey(
        to=Project,
        on_delete=models.RESTRICT,
    )
    uploaded_by = models.ForeignKey(
        to=UserModel,
        on_delete=models.RESTRICT,
    )

    def __str__(self):
        return f"{self.project.base_project.name} - {self.title}"


class ProjectComment(Timestamp, models.Model):
    TEXT_MAX_LENGTH = 300

    text = models.TextField(
        max_length=TEXT_MAX_LENGTH,
        blank=False,
        null=False,
    )
    project = models.ForeignKey(
        to=BaseProject,
        on_delete=models.RESTRICT,
    )
    user = models.ForeignKey(
        to=UserModel,
        on_delete=models.RESTRICT,
    )

    def __str__(self):
        return f"{self.user} - {self.project}"

    class Meta:
        ordering = ["created_at"]

OPM_arch_Project/clients_app/forms.py
from django import forms

from OPM_arch_Project.clients_app.models import Client


class ClientsCreateForm(forms.ModelForm):
    website = forms.URLField(initial='https://')

    class Meta:
        model = Client
        fields = '__all__'
        exclude = ['is_active', 'is_main',]
        help_texts = {
            'name': f'Maximum length of the name is {Client.NAME_MAX_LENGTH} characters.',
            'telephone_number': f'Should consists only of numbers.',
        }


class ClientsUpdateForm(forms.ModelForm):
    website = forms.URLField(initial='https://')

    class Meta:
        model = Client
        fields = '__all__'
        exclude = ['is_active', 'is_main']

OPM_arch_Project/clients_app/views.py
from django.core.exceptions import PermissionDenied
from django.urls import reverse_lazy
from django.views import generic as views
from django.contrib.auth import mixins as auth_mixins

from OPM_arch_Project.clients_app.forms import ClientsCreateForm, ClientsUpdateForm
from OPM_arch_Project.clients_app.models import Client


class ClientsListView(auth_mixins.LoginRequiredMixin, views.ListView):
    model = Client
    template_name = 'clients_app/clients_list.html'


class ClientsDetailView(auth_mixins.LoginRequiredMixin, views.DetailView):
    template_name = 'clients_app/clients_details.html'
    model = Client

    def dispatch(self, request, *args, **kwargs):
        if self.request.user.is_authenticated and not self.check_request_permissions():
            return self.handle_no_permission()

        return super().dispatch(request, *args, **kwargs)

    def check_request_permissions(self):

        if self.request.user.client != self.get_object()\
                and not self.request.user.is_staff:
            raise PermissionDenied

        return True


class ClientsCreateView(auth_mixins.LoginRequiredMixin, views.CreateView):
    template_name = 'clients_app/clients_create.html'
    model = Client
    form_class = ClientsCreateForm

    def dispatch(self, request, *args, **kwargs):
        if self.request.user.is_authenticated and not self.check_request_permissions():
            return self.handle_no_permission()

        return super().dispatch(request, *args, **kwargs)

    def check_request_permissions(self):

        if not self.request.user.is_staff:
            raise PermissionDenied

        return True

    def get_success_url(self):
        return reverse_lazy('clients_details', kwargs={'pk': self.object.pk})


class ClientsUpdateView(auth_mixins.LoginRequiredMixin, views.UpdateView):
    template_name = 'clients_app/clients_update.html'
    model = Client
    form_class = ClientsUpdateForm

    def dispatch(self, request, *args, **kwargs):
        if self.request.user.is_authenticated and not self.check_request_permissions():
            return self.handle_no_permission()

        return super().dispatch(request, *args, **kwargs)

    def check_request_permissions(self):

        if self.request.user.client != self.get_object()\
                and not self.request.user.is_staff:
            raise PermissionDenied
        elif self.request.user.client.is_main:
            if not self.request.user.is_staff:
                raise PermissionDenied

        return True

    def get_success_url(self):
        return reverse_lazy('clients_details', kwargs={'pk': self.object.pk})

templates/clients_app/client_create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}
    Client Create Page
{% endblock %}

{% block content %}

    {% if request.user.is_staff %}


        <div class="container">
            <h2 style="font-size: x-large; border: lightslategrey; border-style: solid; border-radius: 8px"
                class="row justify-content-center col-sm-4">Create New Client</h2>
        </div>

        <br>

        <form class="post-form" method="post" action="{% url 'client_create' %}">

            <div class="container">
                <div class="row justify-content-left">
                    <div class="col-sm-4">

                        {% csrf_token %}

                        {% crispy form %}

                        <button class="btn btn-secondary">Create</button>
                    </div>
                </div>
            </div>

        </form>




    {% else %}
        You do not have permissions for that!
    {% endif %}

{% endblock %}

templates/clients_app/clients_create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}
    Client Create Page
{% endblock %}

{% block content %}

    <div class="container">
        <h2 style="font-size: x-large; border: lightslategrey; border-style: solid; border-radius: 8px"
            class="row justify-content-center col-lg-6">Create New Client</h2>
    </div>

    <br>

    <form class="post-form" method="post" action="{% url 'clients_create' %}">

        <div class="container">
            <div class="row justify-content-left">
                <div class="col-lg-6">

                    {% csrf_token %}

                    {% crispy form %}

                    <button type="submit" class="btn btn-primary">Create</button>
                    <button type="reset" class="btn btn-secondary" onclick="history.back()">Cancel</button>
                </div>
            </div>
        </div>

    </form>

{% endblock %}

templates/clients_app/clients_details.html
{% extends 'base.html' %}

{% block title %}
    Client Details Page
{% endblock %}

{% block content %}

    <div class="card col-lg-6">
        <div class="card-header fw-bold">
            {{ object.name }}
        </div>
        <ul class="list-group list-group-flush">
            <li class="list-group-item">{{ object.street_name }} {{ object.street_number }}
                - {{ object.city }}, {{ object.country }}</li>
            <li class="list-group-item">{{ object.telephone_number }}</li>
            <li class="list-group-item"><a href="{{ object.website }}"
                                           style="text-decoration: none">{{ object.website }}</a></li>
            </ul>
                <a class="btn d-grid " href="{% url 'clients_update' pk=object.pk %}">
                    <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
                </a>

            
    </div>

    <div class="list-group col-lg-6 mt-3">
        <a class="btn btn-outline-dark" data-bs-toggle="collapse"
           href="#collapseClients" role="button" aria-expanded="false" aria-controls="collapseClients">
            <div class="d-flex w-100 justify-content-between">
                <h5 class="mb-1 fw-bold "><i class="bi bi-chevron-down me-2"></i>List of all Projects</h5>
                <small>{{ object.baseproject_set.all.count }} projects</small>
            </div>
        </a>
    </div>


    {% for project in object.baseproject_set.all %}

        <div class="collapse" id="collapseClients">
            <div class="list-group col-lg-6">

                <a href="{% url 'projects_details' pk=project.pk %}" class="list-group-item list-group-item-action"
                   aria-current="true">
                    <div class="d-flex w-100 justify-content-between">
                        <h5 class="mb-1 fw-bold">{{ project.name }}</h5>
                        <small>{{ project.get_project_phase_display }}</small>
                    </div>
                    <p class="mb-1">{{ project.city }}, {{ project.municipality }}</p>
                    <small>{{ project.get_project_type_display }}</small>
                </a>

            </div>
        </div>

    {% endfor %}

{% endblock %}

templates/clients_app/clients_list.html
{% extends 'base.html' %}

{% block title %}
    Client List Page
{% endblock %}

{% block content %}

    <div class="card col-lg-6">
        <div class="card-header fw-bold">
            {{ request.user.client }}
            <a href="{% url 'clients_details' pk=request.user.client.pk %}">
                            <i class="bi bi-pencil-square" style="color: lightslategray"></i>
                        </a>
        </div>
        <ul class="list-group list-group-flush">
            <li class="list-group-item">{{ request.user.client.street_name }} {{ request.user.client.street_number }}
                - {{ request.user.client.city }}, {{ request.user.client.country }}</li>
            <li class="list-group-item">{{ request.user.client.telephone_number }}</li>
            <li class="list-group-item"><a href="{{ request.user.client.website }}"
                                           style="text-decoration: none">{{ request.user.client.website }}</a></li>
        </ul>
    </div>


    {% if request.user.is_staff %}

        <div class="list-group col-lg-6 mt-3">
            <a class="btn btn-dark" data-bs-toggle="collapse"
               href="#collapseClients" role="button" aria-expanded="false" aria-controls="collapseClients">
                <div class="d-flex w-100 justify-content-between">
                    <h5 class="mb-1 fw-bold "><i class="bi bi-chevron-down me-2"></i>List of all Clients</h5>
                    <small>{{ clients_count }} clients | {{ all_projects_count }} projects</small>
                </div>
            </a>
        </div>
        {% for client in client_list %}
            {% if not client.is_main %}
                <div class="collapse" id="collapseClients">
                    <div class="list-group col-lg-6">

                        <a href="{% url 'clients_details' pk=client.pk %}"
                           class="list-group-item list-group-item-action"
                           aria-current="true">
                            <div class="d-flex w-100 justify-content-between">
                                <h5 class="mb-1 fw-bold">{{ client.name }}</h5>
                                <small>{{ client.baseproject_set.all.count }} projects</small>
                            </div>
                            <p class="mb-1">{{ client.city }}, {{ client.country }}</p>
                            <small>{{ client.telephone_number }}</small>
                        </a>

                    </div>
                </div>
            {% endif %}
        {% endfor %}
    {% endif %}

{% endblock %}

templates/clients_app/clients_update.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}
    Client Update Page
{% endblock %}

{% block content %}

        <div class="container">
            <h2 style="font-size: x-large; border: lightslategrey; border-style: solid; border-radius: 8px"
                class="row justify-content-center col-lg-6">{{ object.name }}</h2>
        </div>

        <div class="container">
            <i><a style="text-decoration: none; color: black" href="{{ object.website }}"
                  class="row justify-content-center col-lg-6">{{ object.website }}</a></i>
            <br>
        </div>

        <form class="post-form" method="post" action="">

            <div class="container">
                <div class="row justify-content-left">
                    <div class="col-lg-6">

                        {% csrf_token %}

                        {% crispy form %}

                        <button class="btn btn-primary">Update</button>
                        <button type="reset" class="btn btn-secondary" onclick="history.back()">Cancel</button>
                        
                    </div>
                </div>
            </div>

        </form>

{% endblock %}